package com.esta.backoffice.mapper;

import com.esta.backoffice.model.Administrator;
import com.esta.backoffice.model.AdministratorExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    long countByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int deleteByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int deleteByPrimaryKey(Integer administratorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int insertSelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    List<Administrator> selectByExample(AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    Administrator selectByPrimaryKey(Integer administratorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int updateByExampleSelective(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int updateByExample(@Param("record") Administrator record, @Param("example") AdministratorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int updateByPrimaryKeySelective(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator_t
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    int updateByPrimaryKey(Administrator record);
}