package com.esta.backoffice.mapper;

import com.esta.backoffice.model.Intention;
import com.esta.backoffice.model.IntentionExample;
import com.esta.backoffice.model.IntentionWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IntentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    long countByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int deleteByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int deleteByPrimaryKey(Integer intentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int insert(IntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int insertSelective(IntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    List<IntentionWithBLOBs> selectByExampleWithBLOBs(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    List<Intention> selectByExample(IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    IntentionWithBLOBs selectByPrimaryKey(Integer intentionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") IntentionWithBLOBs record, @Param("example") IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") IntentionWithBLOBs record, @Param("example") IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByExample(@Param("record") Intention record, @Param("example") IntentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByPrimaryKeySelective(IntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(IntentionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    int updateByPrimaryKey(Intention record);
}