package com.esta.backoffice.model;

public class Administrator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator_t.administrator_id
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    private Integer administratorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator_t.administrator_name
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    private String administratorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column administrator_t.administrator_password
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    private String administratorPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator_t.administrator_id
     *
     * @return the value of administrator_t.administrator_id
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public Integer getAdministratorId() {
        return administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator_t.administrator_id
     *
     * @param administratorId the value for administrator_t.administrator_id
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public void setAdministratorId(Integer administratorId) {
        this.administratorId = administratorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator_t.administrator_name
     *
     * @return the value of administrator_t.administrator_name
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public String getAdministratorName() {
        return administratorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator_t.administrator_name
     *
     * @param administratorName the value for administrator_t.administrator_name
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public void setAdministratorName(String administratorName) {
        this.administratorName = administratorName == null ? null : administratorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column administrator_t.administrator_password
     *
     * @return the value of administrator_t.administrator_password
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public String getAdministratorPassword() {
        return administratorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column administrator_t.administrator_password
     *
     * @param administratorPassword the value for administrator_t.administrator_password
     *
     * @mbg.generated Tue Jul 30 22:06:46 CST 2019
     */
    public void setAdministratorPassword(String administratorPassword) {
        this.administratorPassword = administratorPassword == null ? null : administratorPassword.trim();
    }
}