package com.esta.backoffice.model;

public class Intention {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.intention_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private Integer intentionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_name
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String stuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_num
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private Integer stuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_phone
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private Integer stuPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_english
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String stuEnglish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_computer
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String stuComputer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_gpa
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private Float stuGpa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.intention_id
     *
     * @return the value of intention_t.intention_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Integer getIntentionId() {
        return intentionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.intention_id
     *
     * @param intentionId the value for intention_t.intention_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setIntentionId(Integer intentionId) {
        this.intentionId = intentionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.user_id
     *
     * @return the value of intention_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.user_id
     *
     * @param userId the value for intention_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_name
     *
     * @return the value of intention_t.stu_name
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_name
     *
     * @param stuName the value for intention_t.stu_name
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_num
     *
     * @return the value of intention_t.stu_num
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Integer getStuNum() {
        return stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_num
     *
     * @param stuNum the value for intention_t.stu_num
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuNum(Integer stuNum) {
        this.stuNum = stuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_phone
     *
     * @return the value of intention_t.stu_phone
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Integer getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_phone
     *
     * @param stuPhone the value for intention_t.stu_phone
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuPhone(Integer stuPhone) {
        this.stuPhone = stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_english
     *
     * @return the value of intention_t.stu_english
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getStuEnglish() {
        return stuEnglish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_english
     *
     * @param stuEnglish the value for intention_t.stu_english
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuEnglish(String stuEnglish) {
        this.stuEnglish = stuEnglish == null ? null : stuEnglish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_computer
     *
     * @return the value of intention_t.stu_computer
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getStuComputer() {
        return stuComputer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_computer
     *
     * @param stuComputer the value for intention_t.stu_computer
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuComputer(String stuComputer) {
        this.stuComputer = stuComputer == null ? null : stuComputer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_gpa
     *
     * @return the value of intention_t.stu_gpa
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Float getStuGpa() {
        return stuGpa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_gpa
     *
     * @param stuGpa the value for intention_t.stu_gpa
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuGpa(Float stuGpa) {
        this.stuGpa = stuGpa;
    }
}