package com.esta.backoffice.model;

public class IntentionWithBLOBs extends Intention {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.stu_resume
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String stuResume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.race_proposed
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String raceProposed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column intention_t.award_remark
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    private String awardRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.stu_resume
     *
     * @return the value of intention_t.stu_resume
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getStuResume() {
        return stuResume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.stu_resume
     *
     * @param stuResume the value for intention_t.stu_resume
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setStuResume(String stuResume) {
        this.stuResume = stuResume == null ? null : stuResume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.race_proposed
     *
     * @return the value of intention_t.race_proposed
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getRaceProposed() {
        return raceProposed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.race_proposed
     *
     * @param raceProposed the value for intention_t.race_proposed
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setRaceProposed(String raceProposed) {
        this.raceProposed = raceProposed == null ? null : raceProposed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column intention_t.award_remark
     *
     * @return the value of intention_t.award_remark
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getAwardRemark() {
        return awardRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column intention_t.award_remark
     *
     * @param awardRemark the value for intention_t.award_remark
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setAwardRemark(String awardRemark) {
        this.awardRemark = awardRemark == null ? null : awardRemark.trim();
    }
}