package com.esta.backoffice.model;

import java.util.ArrayList;
import java.util.List;

public class IntentionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public IntentionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIntentionIdIsNull() {
            addCriterion("intention_id is null");
            return (Criteria) this;
        }

        public Criteria andIntentionIdIsNotNull() {
            addCriterion("intention_id is not null");
            return (Criteria) this;
        }

        public Criteria andIntentionIdEqualTo(Integer value) {
            addCriterion("intention_id =", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdNotEqualTo(Integer value) {
            addCriterion("intention_id <>", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdGreaterThan(Integer value) {
            addCriterion("intention_id >", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("intention_id >=", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdLessThan(Integer value) {
            addCriterion("intention_id <", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdLessThanOrEqualTo(Integer value) {
            addCriterion("intention_id <=", value, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdIn(List<Integer> values) {
            addCriterion("intention_id in", values, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdNotIn(List<Integer> values) {
            addCriterion("intention_id not in", values, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdBetween(Integer value1, Integer value2) {
            addCriterion("intention_id between", value1, value2, "intentionId");
            return (Criteria) this;
        }

        public Criteria andIntentionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("intention_id not between", value1, value2, "intentionId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNull() {
            addCriterion("stu_name is null");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNotNull() {
            addCriterion("stu_name is not null");
            return (Criteria) this;
        }

        public Criteria andStuNameEqualTo(String value) {
            addCriterion("stu_name =", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotEqualTo(String value) {
            addCriterion("stu_name <>", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThan(String value) {
            addCriterion("stu_name >", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThanOrEqualTo(String value) {
            addCriterion("stu_name >=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThan(String value) {
            addCriterion("stu_name <", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThanOrEqualTo(String value) {
            addCriterion("stu_name <=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLike(String value) {
            addCriterion("stu_name like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotLike(String value) {
            addCriterion("stu_name not like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameIn(List<String> values) {
            addCriterion("stu_name in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotIn(List<String> values) {
            addCriterion("stu_name not in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameBetween(String value1, String value2) {
            addCriterion("stu_name between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotBetween(String value1, String value2) {
            addCriterion("stu_name not between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNumIsNull() {
            addCriterion("stu_num is null");
            return (Criteria) this;
        }

        public Criteria andStuNumIsNotNull() {
            addCriterion("stu_num is not null");
            return (Criteria) this;
        }

        public Criteria andStuNumEqualTo(Integer value) {
            addCriterion("stu_num =", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumNotEqualTo(Integer value) {
            addCriterion("stu_num <>", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumGreaterThan(Integer value) {
            addCriterion("stu_num >", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_num >=", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumLessThan(Integer value) {
            addCriterion("stu_num <", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumLessThanOrEqualTo(Integer value) {
            addCriterion("stu_num <=", value, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumIn(List<Integer> values) {
            addCriterion("stu_num in", values, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumNotIn(List<Integer> values) {
            addCriterion("stu_num not in", values, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumBetween(Integer value1, Integer value2) {
            addCriterion("stu_num between", value1, value2, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuNumNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_num not between", value1, value2, "stuNum");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIsNull() {
            addCriterion("stu_phone is null");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIsNotNull() {
            addCriterion("stu_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStuPhoneEqualTo(Integer value) {
            addCriterion("stu_phone =", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotEqualTo(Integer value) {
            addCriterion("stu_phone <>", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneGreaterThan(Integer value) {
            addCriterion("stu_phone >", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_phone >=", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneLessThan(Integer value) {
            addCriterion("stu_phone <", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneLessThanOrEqualTo(Integer value) {
            addCriterion("stu_phone <=", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIn(List<Integer> values) {
            addCriterion("stu_phone in", values, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotIn(List<Integer> values) {
            addCriterion("stu_phone not in", values, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneBetween(Integer value1, Integer value2) {
            addCriterion("stu_phone between", value1, value2, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_phone not between", value1, value2, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuEnglishIsNull() {
            addCriterion("stu_english is null");
            return (Criteria) this;
        }

        public Criteria andStuEnglishIsNotNull() {
            addCriterion("stu_english is not null");
            return (Criteria) this;
        }

        public Criteria andStuEnglishEqualTo(String value) {
            addCriterion("stu_english =", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishNotEqualTo(String value) {
            addCriterion("stu_english <>", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishGreaterThan(String value) {
            addCriterion("stu_english >", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishGreaterThanOrEqualTo(String value) {
            addCriterion("stu_english >=", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishLessThan(String value) {
            addCriterion("stu_english <", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishLessThanOrEqualTo(String value) {
            addCriterion("stu_english <=", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishLike(String value) {
            addCriterion("stu_english like", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishNotLike(String value) {
            addCriterion("stu_english not like", value, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishIn(List<String> values) {
            addCriterion("stu_english in", values, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishNotIn(List<String> values) {
            addCriterion("stu_english not in", values, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishBetween(String value1, String value2) {
            addCriterion("stu_english between", value1, value2, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuEnglishNotBetween(String value1, String value2) {
            addCriterion("stu_english not between", value1, value2, "stuEnglish");
            return (Criteria) this;
        }

        public Criteria andStuComputerIsNull() {
            addCriterion("stu_computer is null");
            return (Criteria) this;
        }

        public Criteria andStuComputerIsNotNull() {
            addCriterion("stu_computer is not null");
            return (Criteria) this;
        }

        public Criteria andStuComputerEqualTo(String value) {
            addCriterion("stu_computer =", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerNotEqualTo(String value) {
            addCriterion("stu_computer <>", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerGreaterThan(String value) {
            addCriterion("stu_computer >", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerGreaterThanOrEqualTo(String value) {
            addCriterion("stu_computer >=", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerLessThan(String value) {
            addCriterion("stu_computer <", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerLessThanOrEqualTo(String value) {
            addCriterion("stu_computer <=", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerLike(String value) {
            addCriterion("stu_computer like", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerNotLike(String value) {
            addCriterion("stu_computer not like", value, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerIn(List<String> values) {
            addCriterion("stu_computer in", values, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerNotIn(List<String> values) {
            addCriterion("stu_computer not in", values, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerBetween(String value1, String value2) {
            addCriterion("stu_computer between", value1, value2, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuComputerNotBetween(String value1, String value2) {
            addCriterion("stu_computer not between", value1, value2, "stuComputer");
            return (Criteria) this;
        }

        public Criteria andStuGpaIsNull() {
            addCriterion("stu_gpa is null");
            return (Criteria) this;
        }

        public Criteria andStuGpaIsNotNull() {
            addCriterion("stu_gpa is not null");
            return (Criteria) this;
        }

        public Criteria andStuGpaEqualTo(Float value) {
            addCriterion("stu_gpa =", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaNotEqualTo(Float value) {
            addCriterion("stu_gpa <>", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaGreaterThan(Float value) {
            addCriterion("stu_gpa >", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaGreaterThanOrEqualTo(Float value) {
            addCriterion("stu_gpa >=", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaLessThan(Float value) {
            addCriterion("stu_gpa <", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaLessThanOrEqualTo(Float value) {
            addCriterion("stu_gpa <=", value, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaIn(List<Float> values) {
            addCriterion("stu_gpa in", values, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaNotIn(List<Float> values) {
            addCriterion("stu_gpa not in", values, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaBetween(Float value1, Float value2) {
            addCriterion("stu_gpa between", value1, value2, "stuGpa");
            return (Criteria) this;
        }

        public Criteria andStuGpaNotBetween(Float value1, Float value2) {
            addCriterion("stu_gpa not between", value1, value2, "stuGpa");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table intention_t
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 30 22:29:51 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table intention_t
     *
     * @mbg.generated Tue Jul 30 22:29:51 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}