package com.esta.backoffice.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_name
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_password
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_number
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private Integer userNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_pp
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private Integer userPp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_t.user_phone
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    private Integer userPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_id
     *
     * @return the value of user_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_id
     *
     * @param userId the value for user_t.user_id
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_name
     *
     * @return the value of user_t.user_name
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_name
     *
     * @param userName the value for user_t.user_name
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_password
     *
     * @return the value of user_t.user_password
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_password
     *
     * @param userPassword the value for user_t.user_password
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_number
     *
     * @return the value of user_t.user_number
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public Integer getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_number
     *
     * @param userNumber the value for user_t.user_number
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserNumber(Integer userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_pp
     *
     * @return the value of user_t.user_pp
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public Integer getUserPp() {
        return userPp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_pp
     *
     * @param userPp the value for user_t.user_pp
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserPp(Integer userPp) {
        this.userPp = userPp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_t.user_phone
     *
     * @return the value of user_t.user_phone
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public Integer getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_t.user_phone
     *
     * @param userPhone the value for user_t.user_phone
     *
     * @mbg.generated Tue Jul 30 22:08:13 CST 2019
     */
    public void setUserPhone(Integer userPhone) {
        this.userPhone = userPhone;
    }
}